version: '2'
services:
  #databaseapp:
    #image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    #environment:
    #  MYSQL_DATABASE: db_logbook
    #  MYSQL_USER: nata
    #  MYSQL_PASSWORD: nata
    #  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    #ports:
    #  - '3305:3306'
  aplikasi:
    #image: yiisoftware/yii2-php:7.1-apache
    build: .
    #volumes:
    #  - ~/.composer-docker/cache:/root/.composer/cache:delegated
    #  - ./:/var/www/html:delegated
    ports:
      - '8080:80'
    #depends_on:
    #  - 'databaseapp'
  

